DROP DATABASE IF EXISTS Macrofitas;
CREATE DATABASE Macrofitas;
USE Macrofitas;

CREATE TABLE OCORRENCIA(
	ID INTEGER NOT NULL auto_increment,
	FONTE VARCHAR(100),
	NOME VARCHAR(200),
	COLETADOR VARCHAR(200),
	LOCATION VARCHAR(2000),
	PAIS VARCHAR(100),
	ESTADO VARCHAR(100),
	CIDADE VARCHAR(100),
	LATITUDE VARCHAR(50),
	LONGITUDE VARCHAR(50),
	ANO_COLETA VARCHAR(4),
	MES_COLETA VARCHAR(2),
	DIA_COLETA VARCHAR(2),
	PRIMARY KEY(ID)
);

CREATE TABLE PLANT(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	FONTE VARCHAR(50),
	ESTADO VARCHAR(10),
	HIERARQUIATAXONOMICA VARCHAR(100),
	FAMILIA VARCHAR(100),
	FORMA_VIDA VARCHAR(200),
	SUBSTRATO VARCHAR(100),
	ORIGEM VARCHAR(100),
	ENDEMISMO VARCHAR(100),
	POSSIVEIS_OCORRENCIAS VARCHAR(300),
	DOMINIOS_FITEOGEOGRAFICOS VARCHAR(500),
	TIPO_VEGETACAO VARCHAR(500),
	ID_SINONIMO INTEGER,
	PRIMARY KEY(ID),
	FOREIGN KEY (ID_SINONIMO) REFERENCES PLANT(ID)
);

CREATE TABLE SINONIMO(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	FONTE VARCHAR(50),
	ESTADO VARCHAR(10),
	HIERARQUIATAXONOMICA VARCHAR(100),
	FAMILIA VARCHAR(100),
	FORMA_VIDA VARCHAR(200),
	SUBSTRATO VARCHAR(100),
	ORIGEM VARCHAR(100),
	ENDEMISMO VARCHAR(100),
	POSSIVEIS_OCORRENCIAS VARCHAR(300),
	DOMINIOS_FITEOGEOGRAFICOS VARCHAR(500),
	TIPO_VEGETACAO VARCHAR(500),
	ID_PLANTA INTEGER,
	PRIMARY KEY(ID),
	FOREIGN KEY (ID_PLANTA) REFERENCES PLANT(ID)
);


CREATE TABLE PLANTATHEPLANTLIST(
	ID INTEGER NOT NULL auto_increment,
	PLANTA VARCHAR(200),	
	AUTOR VARCHAR(200),
	PRIMARY KEY(ID)
);

CREATE TABLE SINONIMOS_PLANTLIST(
	ID INTEGER NOT NULL auto_increment,	
	NOME VARCHAR (100),
	ID_PLANTA_CORRETA INTEGER,	
	AUTOR VARCHAR(200),	
	FOREIGN KEY(ID_PLANTA_CORRETA) REFERENCES PLANTATHEPLANTLIST(ID),
	PRIMARY KEY(ID)
);